name: worksuite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  ky_docs:
    path: ../Modules/ky_docs
  ky_sheet:
    path: ../Modules/ky_sheet
  ky_slide:
    path: ../Modules/ky_slide
  ky_office_core:
    path: ../Modules/ky_office_core
  ky_office:
    path: ../Modules/ky_office
    
  flutter_riverpod: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
